wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    code_path: code/trl/bin_gptx-neo.py
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1681423192.673427
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.9.15
      5: 0.14.0
      6: 4.27.4
      8:
      - 8
