defaults:
  - _self_
  - model: phi2
  - peft_config: default
  - generation_kwargs: default
  - curriculum_schedule: mixed_zero_one
  - inference_generation_kwargs: default
  - ppo_config: default
  - acc_maintain: default

################################################################################
# For no-training stats
################################################################################
no_training: False
max_epochs: null

################################################################################
# Top Importance
################################################################################
answer_only: False

batch_size: 16
use_curriculum: True
input_max_length: 115
name: "acc_maintain=${acc_maintain}_model_name=${model.model_name}_num_beams=${generation_kwargs.num_beams}"
value_pretrain_epochs: null
answer_only_max_length: 15

eval_every: 0
use_peft: True
just_metrics: False
eval_subset_size: 0
reward_type: exact_match
precision: float32
wandb_project: rl_${dataset_name}

float32_precision_generation: "highest"
float32_precision_forward_backward: "highest"


################################################################################
# This should never change
################################################################################
use_few_shots: True
dataset_name: arithmetic
task_name: main
peft_do_all_lin_layers: False
arithmetic_dataset_root_folder_dir: "/home/mila/g/gagnonju/marglicot/with_trl/libs_data/arithmetic/"
answer_only_path: "/network/scratch/g/gagnonju/saved_scratchpad_gen_outputs/chatgpt-3.5-commonsenseqa-scratchpads/not-cond-on-answers/commonsenseqa.chatgpt"
