_wandb:
    value:
        cli_version: 0.18.1
        code_path: code/with_open-instruct/open-instruct/open_instruct/ppo_vllm_thread_ray_gtrl.py
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 55
                - 71
                - 95
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 55
                - 71
                - 95
                - 105
            "3":
                - 13
                - 15
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.14
            "5": 0.18.1
            "6": 4.46.2
            "8":
                - 8
            "12": 0.18.1
            "13": linux-x86_64
actor_num_gpus_per_node:
    value:
        - 3
answer_extraction_model:
    value: null
apply_verifiable_reward:
    value: true
async_mode:
    value: true
attn_implementation:
    value: null
batched:
    value: false
beta:
    value: 0.05
binary_messages_key:
    value: messages
bnb_4bit_quant_type:
    value: nf4
chat_template:
    value: simple_chat
checkpoint_output_dir:
    value: null
cliprange:
    value: 0.2
cliprange_value:
    value: 0.2
convert_preference_to_binary_dataset:
    value: false
dataset_eval_mixer:
    value: null
dataset_eval_mixer_dict:
    value: null
dataset_eval_splits:
    value: null
dataset_mixer:
    value: '{"ai2-adapt-dev/gsm8k_math_ground_truth": 1.0}'
dataset_mixer_dict:
    value:
        ai2-adapt-dev/gsm8k_math_ground_truth: 1
dataset_source_key:
    value: dataset
dataset_train_splits:
    value:
        - train
deepspeed_stage:
    value: 3
enable_prefix_caching:
    value: false
eps:
    value: 1e-05
eval_freq:
    value: 34722
exp_name:
    value: ppo_vllm_thread_ray_gtrl
gamma:
    value: 1
gather_whole_model:
    value: true
gradient_accumulation_steps:
    value: 16
gradient_checkpointing:
    value: false
ground_truths_key:
    value: ground_truth
hf_entity:
    value: JulesGM
hf_metadata_dataset:
    value: allenai/tulu-3-evals
hf_repo_id:
    value: JulesGM/open_instruct_dev
hf_repo_revision:
    value: ppo_vllm_thread_ray_gtrl__3__1735683176
hf_repo_url:
    value: https://huggingface.co/JulesGM/open_instruct_dev/tree/ppo_vllm_thread_ray_gtrl__3__1735683176
init_value_from_scratch:
    value: false
kl_estimator:
    value: kl1
label:
    value: binary_labels
lam:
    value: 0.95
learning_rate:
    value: 3e-07
load_from_cache_file:
    value: true
load_in_4bit:
    value: false
load_in_8bit:
    value: false
local_dataloader_batch_size:
    value: 96
local_mini_batch_size:
    value: 32
local_rollout_batch_size:
    value: 32
local_rollout_forward_batch_size:
    value: 2
lora_alpha:
    value: 32
lora_dropout:
    value: 0.05
lora_modules_to_save:
    value: null
lora_r:
    value: 16
lora_target_modules:
    value: null
lora_task_type:
    value: CAUSAL_LM
lr_scheduler_type:
    value: linear
max_prompt_token_length:
    value: 2048
max_token_length:
    value: 2048
micro_batch_size:
    value: 6
min_response_length:
    value: 0
mini_batch_size:
    value: 96
model_name_or_path:
    value: HuggingFaceTB/SmolLM2-1.7B-Instruct
model_revision:
    value: null
ncols:
    value: 2
non_stop_penalty:
    value: true
num_epochs:
    value: 4
num_evals:
    value: 3
num_mini_batches:
    value: 1
num_proc:
    value: 48
num_train_epochs:
    value: 1
num_training_steps:
    value: 104166
number_samples_per_prompt:
    value: 1
oe_eval_tasks:
    value: null
output_dir:
    value: /network/scratch/g/gagnonju/open_instruct_output/2024-12-31_17-12-35_rlvr_gsm8k_only_smollm2_instruct_simple_chat
penalty_reward_value:
    value: -10
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 2
preference_chosen_key:
    value: chosen
preference_rejected_key:
    value: rejected
push_to_hub:
    value: true
response_length:
    value: 2048
reward_model_multiplier:
    value: 0
reward_model_path:
    value: HuggingFaceTB/SmolLM2-1.7B-Instruct
reward_model_revision:
    value: null
rollout_batch_size:
    value: 96
run_name:
    value: ppo_vllm_thread_ray_gtrl__3__1735683176
sanity_check:
    value: false
sanity_check_max_samples:
    value: 100
save_freq:
    value: 100
seed:
    value: 3
sft_messages_key:
    value: messages
stop_token:
    value: eos
stop_token_id:
    value: null
temperature:
    value: 1
torch_dtype:
    value: null
total_episodes:
    value: 10000000
train_only_on_prompt:
    value: false
trust_remote_code:
    value: false
try_launch_beaker_eval_jobs:
    value: true
try_launch_beaker_eval_jobs_on_weka:
    value: false
use_bnb_nested_quant:
    value: false
use_cache:
    value: null
use_peft:
    value: false
vf_coef:
    value: 0.1
vllm_num_engines:
    value: 1
vllm_sync_backend:
    value: nccl
vllm_tensor_parallel_size:
    value: 1
wandb_entity:
    value: julesgm
wandb_project_name:
    value: open_instruct_rl
warm_up_steps:
    value: 0
warmup_ratio:
    value: 0
whiten_rewards:
    value: false
with_tracking:
    value: true
world_size:
    value: 3
