train:
  ##########################################################################################
  batch_size: 256 # To be changed
  ##########################################################################################
  
  reward_fn_is_distributed: True
  seq_length: 320
  epochs: 100
  total_steps: 10000
  checkpoint_interval: 10000
  eval_interval: 100
  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"

model:
  num_layers_unfrozen: 2
  model_arch_type: "seq2seq"

tokenizer:
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 1.0e-4

method:
  ##########################################################################################
  chunk_size: 256 # ?
  num_rollouts: 32 # Should be 128 ?
  ##########################################################################################
  
  name: "ppoconfig"
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  
  gen_kwargs:
    synced_gpus: True
    max_new_tokens: 200
    num_beams: 6
    do_sample: True
